files:
  ignore:
    - "**/test/assets/sass/compass/**/*.scss"
    - "**/test/assets/sass_private/compass/**/*.scss"
rules:
  indentation:
    - 2
    - size: 2
  no-misspelled-properties:
    - 1
    - extra-properties:
        - critical
